services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx

    ports:
      - "8554:8554"        # RTSP
      - "8889:8889"        # Web UI
      - "8189:8189"        # metrics/api
      - "8888:8888/udp"    # MPEG-TS ingest

      - "8189:8189/udp"
      - "50000-50100:50000-50100/udp"

    volumes:
      - ../mediamtx.yml:/mediamtx.yml

    command: /mediamtx.yml

    restart: unless-stopped

  imageextractor:
    image: linuxserver/ffmpeg:latest
    depends_on:
      - mediamtx
    restart: unless-stopped

    volumes:
      - ../img/snapshots:/img/snapshots

    command: -rtsp_transport tcp -i rtsp://mediamtx:8554/cam -vf fps=1/60 -update 1 -y /img/snapshots/latest.jpg